### PR TITLE
Ignore tasks when Java 8

### PR DESCRIPTION
**Pull request by tomasbjerre**
I want to verify my code on 8/11/17.

With this change, the code formatting will be verified on 11 and 17 and ignored on 8.

### CODE REVIEW

**Comment by sherter** [comment]
Sorry, but dropping Java 8 runtime support for no reason (with questionable "ignore" semantics) is not going to happen. Consider using custom format/verify tasks (see README) to implement this behavior if you must.

**Comment by tomasbjerre** [comment]
I might be wrong, but there is no way of using this plugin with JDK 8. Because of the formatting library from Google (https://github.com/sherter/google-java-format-gradle-plugin/issues/61).

This would make it easy to use a recent version of this plugin and still be able to build the application with JDK 8 (without formatting).

Totally ok with not getting it merged. I do it like this now:

```groovy
  if (JavaVersion.current() != JavaVersion.VERSION_1_8) {
    apply plugin: com.github.sherter.googlejavaformatgradleplugin.GoogleJavaFormatPlugin
    build.dependsOn 'googleJavaFormat'
    verifyGoogleJavaFormat.enabled = false

    googleJavaFormat {
      include '**/*.java'
    }

    effectiveConfig.generatedSourceFolders.each {
      googleJavaFormat {
        exclude "${it}/**/*.java"
      }
    }
  } else {
    logger.lifecycle("Skipping googleJavaFormat for ${JavaVersion.current()}")
  }
```

**Comment by sherter** [comment]
You are right, newer versions of google-java-format require Java 11 (starting with v1.8). For sure, at some point I will drop support for those older versions and start requiring Java 11 for this plugin as well, but currently I have no reason to do so.

**Comment by sherter** [comment]
> I might be wrong, but there is no way of using this plugin with JDK 8. Because of the formatting library from Google (#61).

Just to make this absolutely clear, there _is_ a way: Set `toolVersion = '1.7'` (or lower)

**Pull request closed without merging**
